### ISSUE TITLE
Not returning all IPs

### ISSUE THREAD

**Issue by cwallace** [ChrisRidings/PHPmDNS#1]
Sorry, this may not be an issue with the mdns.php specifically, but I'm not knowledgeable enough to figure out exactly where the problem is. Using your example code to find chromecasts, it is identifying all of my chromecast devices properly, but only filling in the IP addresses on some of them:

{"Google-Home-f0f785aa3001e8114a632a936e14aed5._googlecast._tcp.local":{"port":8009,"ip":"192.168.1.41","target":"f0f785aa-3001-e811-4a63-2a936e14aed5.local"},"Chromecast-8ef11feb054d01bff5a24e4685e4cee8._googlecast._tcp.local":{"port":8009,"ip":"","target":"8ef11feb-054d-01bf-f5a2-4e4685e4cee8.local"},"Google-Home-51ab0e90e74926d8fbc470c9583f7dbc._googlecast._tcp.local":{"port":8009,"ip":"","target":"51ab0e90-e749-26d8-fbc4-70c9583f7dbc.local"},"Chromecast-bd029ac346776def5e3af9f600c6de6d._googlecast._tcp.local":{"port":8009,"ip":"","target":"bd029ac3-4677-6def-5e3a-f9f600c6de6d.local"}}

Any ideas on how to troubleshoot?

**Comment by ChrisRidings** [comment]
It's probably timing out. Change the two lines in example that read: $cc=5;  to a bigger number. e.g. $cc=15;  (or higher) . From the json you gave you only need to change the second one, but you may as well change both.

**Comment by cwallace** [comment]
That fixed it. Thank you!
